name: Execution Automatique Toutes les 32 Minutes

on:
  schedule:
    - cron: '*/32 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Recuprer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer Playwright et navigateurs
        run: |
          pip install playwright
          playwright install chromium

      - name: Lancer la tache automatisee
        run: python script.py

      - name: Sauvegarder la capture d ecran de controle
        uses: actions/upload-artifact@v4
        with:
          name: preuve-visuelle
          path: resultat.png
