name: Execution Automatique Toutes les 32 Minutes

on:
  schedule:
    # Ce code dit au serveur GitHub de se lancer toutes les 32 minutes
    - cron: '*/32 * * * *'
  workflow_dispatch: # Permet aussi de lancer le script à la main si besoin

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer Playwright et navigateurs
        run: |
          pip install playwright
          playwright install chromium

      - name: Lancer la tâche automatisée
        run: python script.py
